### ISSUE TITLE
Dúvida - Quebra dos testes

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [kovihq/projeto-vue-cypress#1]
@patrickmonteiro, ficou muito bom o seu post e bem didático 🎉

Uma dúvida que fiquei apenas é sobre a quebra do teste. O teste criado é para fazer um teste simples do formulário e está dividido entre vários `it`, fazendo com que o teste em si seja todos os `it` do `describe`.

Não seria interessante todo o teste ficar dentro de um único `it` e o describe ser um pouco mais genérico para poder abranger outros testes?
Acredito que assim será garantido que se alguma etapa quebrar as outras não serão executadas e também vai resultar em maior legibilidade e manutenibilidade.

## Exemplo

```diff
-describe('Testando Formulário', () => {
+describe('Formulário', () => {
-  it('Acessando rota de Formulário', () => {
-    cy.visit('/form')
-  })
-
-  it('Botão Visível', () => {
-    cy.get('button').should('be.visible')
-  })
-
-  it('Clicando no botão', () => {
-    cy.get('button').click()
-  })
+  it('Testando Formulário', () => {
+    cy.visit('/form'){
+    cy.get('button').should('be.visible')
+    cy.get('button').click()
+  })
.... (resto do teste)
})
```

**Comment by patrickmonteiro** [comment]
@PauloGoncalvesBH desculpe pela demora das respostas.
O Cypress lhe dá a liberdade para fazer como vc achar melhor, eu dividi cada **it()** justamente para que seja possível documentar de forma mais específica o que está sendo feito. Pois no final das contas, nos testes em pipeline não será exibido um navegador mostrando os testes, e sim no terminal utilizando o comando "**cypress run**", dessa forma os testes são executados em "_background_" sem exibir um navegador passo a passo. 

E ai quando se está no terminal, vc precisa saber com mais detalhes onde o teste acusou erro. Mais ou menos assim:
![image](https://user-images.githubusercontent.com/13258255/91103451-df30c700-e641-11ea-8bd3-49da0aacf3d6.png)


E por fim, você pode parar os testes quando existir uma falha, dê uma olhada neste link: https://github.com/cypress-io/cypress/issues/518#issuecomment-373369129


Obrigado pelo seu comentário =)
